# Travis CI now working and approved for Kotlin For FRC

language: nodejs

cache: npm

sudo: true

node_js:
  - "node"

os:
  - linux

# notifications:
#   webhooks: 
#     urls: 
#       - https://api.opsgenie.com/v1/json/travisci?apiKey=f04518a7-c66b-44f9-975d-b8e4ef163a91
#     on_success: always
#     on_failure: always
#   slack: 
#     - secure: 
#     on_success: always
#     on_failure: always

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install

script:
  - npm run compile
  - vsce package
  - npm run test --silent
