# Travis CI now working and approved for Kotlin For FRC

language: nodejs

cache: npm

sudo: true

node_js:
  - "node"

os:
  - linux

notifications:
  # webhooks: 
    # urls: 
      # - https://api.opsgenie.com/v1/json/travisci?apiKey=f04518a7-c66b-44f9-975d-b8e4ef163a91
    # on_success: always
    # on_failure: always
  slack: 
    - secure: "nbXOfG1Tzic9Z5TyvUCSI/4RFxdY0yHRuv+dvZjXaVJPEtrSlcNCSZWsxZwvjsc8XJw3zZdiip8BaDjS4z7YdDfuGChGT/cljgNKIoRURxwbzWwvCKbeMWgMQDFqjW6p9X+yAxRAwgQPFnNg/MVThnQ1A96kuJmTXtvuXBfZN3M4sd8mNbZl2FaT4V8YJw8DT/Q6Xf94qOifLZD4W2W+E8lwHoJnbW1YeXnhR+HSjDw9DhIoqo+goUQeAaazF1z6grf47UfnTHcjHz9CSRjUqFgeMmxTxp1DlX/swk4MNO50s7eayvCoWYZv13ZyNNzeBR7h+8DmLzYQRCnibdAVOTiTNydcfDiyWYBoB78Xcpmwt2xFv0I5EUVGayqI+vyTJi1yh2eIlg28tzJE5TVlszPIsmjkQIFuIR2XAAmuRZHMAheG9JobNTePKvQmPJ9tDESsZ05dpjUVF1ljgAflxdNn8ayRh2HKoyagM98eklzAMKtnePXDWPKjBLQ9PE/3AMnzoX4YWkytPOpaP7WsNifIr+2cJ+GYwzxThGyXWEeBzeLNXP8UXwoWB4lnE4C3jU+lfEzXZUwGSIXhqo1nLycQbLISDQ3dhSSUELvtjeO6c7YZ06vYhTNJtA3pGLHVDKqcCp1l41jL/fXP9+mDtkFDGmwjiCYT+cu797To52Y="
    on_success: always
    on_failure: always

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install

script:
  - npm run compile
  - vsce package
  - npm run test --silent
