language: nodejs

cache: npm

sudo: true

node_js:
  - "node"

install:
  - npm install -g vsce
  - npm install -g typescript
  - npm install

script:
  - npm run compile
  - vsce package
  # - npm test --silent