name: "Post Release Checklist"
description: "Posts a checkable list of everything that needs to happen before a version gets released."
inputs:
  github-token:
    description: Github Token
    required: true

runs:
  using: "node22"
  main: "lib/index.js"
