name: Lint Code Base

on:
  push:
    branches: [development]
  pull_request:
    branches: ["**/*"]

jobs:
  lint-md-ts:
    name: Lint Markdown and Typescript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_MARKDOWN: true
          VALIDATE_TYPESCRIPT_ES: true
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
