name: Release Checklist

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Parse head_ref
        shell: bash
        run: |
          [[ ${{ github.head_ref }} =~ release-.* ]] && echo "HEAD_REF_VALID=true" > $GITHUB_ENV || echo "HEAD_REF_VALID=false" > $GITHUB_ENV

      - name: Parse base_ref
        shell: bash
        run: |
          [[ ${{ github.base_ref }} == master ]] && echo "BASE_REF_VALID=true" > $GITHUB_ENV || echo "BASE_REF_VALID=false" > $GITHUB_ENV

      - name: Comment build results
        uses: actions/github-script@v4
        if: "${{ env.HEAD_REF_VALID }} == 'true' && ${{ env.BASE_REF_VALID }} == 'true'"
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "It looks like you've opened a release PR!\nHere's a handy checklist of things that need to be done before a release.\n\n- [ ] Update RELEASE_NOTES.md\n- [ ] Update CHANGELOG.md\n- [ ] Update Changelog Webview HTML\n- [ ] Update version"
            })
